### ISSUE TITLE
Doesn't support charge

### ISSUE THREAD

**Issue by juliohm** [Eben60/ChemFormulae.jl#1]
Strings like `“ZnFe3+2O4”` fail.

**Comment by Eben60** [comment]
Currently the parser borrowed from https://zlatanvasovic.github.io/ChemEquations.jl/ is used, however the parser is to be re-written completely anyway.

Thanks for reporting, this special case is to be considered along with others (fractional indices, decimal comma, nested parens, functional groups like Me, Eth, Ph...)

**Comment by Eben60** [comment]
I'm slowly starting to realize what a rabbit hole we are approaching. It's one thing to write a parser for formulas written to specified and unambiguous rules, and another one to try to parse chemical formulas "in the wild". Specifically sub- and superscripts and charges could a problem. 

Let's look onto example of yours. What is the total charge of the whole `ZnFe3+2O4` unit? According to arithmetic that should +6. But no, that is of course zero. The charge is indicated to specify the oxidation state of iron (which otherwise could be 2+ just as well), whereas for Zn and O the oxidation states are the "obvious" 2+ and 2- resp. 

Now let`s look onto sulfate anion. Is it SO₄²⁺ or SO²⁺₄ ? Do we represent it as SO42+ or SO2+4 ? The first way can be parsed as (SO42)1+ or S((O42)+), in both cases you have 42 oxygens, and the whole charge of either 1+ or 42+ . It we write it as SO2+4, exactly the same way as our Zinc ferrite - does the charge 2+ refers to the whole group or to each oxygen? For our ferrite, it refers to each iron. For sulfate ion, to the whole ion. 

Now, let's make sulfuric acid with our anion, but let it be monoisotopic: H₂³⁴SO₄ . Or H234SO4, which is the same. Or not exactly?

Another question: [Zink ferrite](https://en.wikipedia.org/wiki/Zinc_ferrite) , whether as a mineral or in a ferrite core in your computer, is typically 
`[(Zn2+)x(Fe2+)1-x](Fe3+)2(O2-)4`, which can be written as `ZnxFe3−xO4` or `(Zn, Fe)Fe2O4`.  In some cases `x` is specified, in others not. What should we do about it?

I can think of some kind of plausibility check for some cases, but the whole doesn't look like a (small & elegant & useful) package anymore. I've also checked what is available in Python - there are some packages, but they seem to deal with "regular" cases only. 

@juliohm , what do you think about it? Especially is it possible to get some information whether the indices are sub- or superscripts? And also, what is the scope of you application?

**Comment by juliohm** [comment]
@Eben60 I am working with the International Mineral Association (IMA) standard. The following tool can be used to export all minerals accepted by IMA with their respective formulas as strings:

https://rruff.info/ima

Got to the bottom left corner of the website, choose IMA Chemistry (plain) and ask to VIEW IN TABLE FORMAT or DOWNLOAD CSV. If the package could target this limited (yet comprehensive) scope, that would be very useful already.

**Comment by Eben60** [comment]
OK, there are representations which can be parsed in an unambiguous way: 
`RRUFF Chemistry (plain)` | `RRUFF Chemistry (concise)` |  etc.

Let's see.

**Comment by juliohm** [comment]
Closing the issue. Thanks for the help and for the package!
